---
# tasks file for Initialise swarm

- name: Init a new swarm with default parameters 
  docker_swarm:
    state: present 
  register: swarm_info 

- name: Debug swarm 
  debug: 
    msg: "{{ swarm_info }}"
