---
# tasks file for Install Docker

- name: Install dependencies
  apt:
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg 
      - lsb-release
      - python3
      - python3-pip
      - python3-docker

    update_cache: true 
  
- name: Add key 
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Setup stable repo 
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable"

- name: Install Docker engine 
  apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    update_cache: true 

- name: docker-python-package
  pip: 
    name: docker 

 

