all:
  hosts:
    docker-manager:
    nginx-load-balancer:
  children:
    workers:
      hosts:
        docker-worker:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
  

    