- hosts: nginx-load-balancer
  become: true 
  roles:
    - Configure NGINX

- hosts: 
    - docker-manager 
    - workers 
  become: true 
  roles:
    - Install Docker 

- hosts: docker-manager
  become: true 
  roles:
    - Initialise Swarm  

- hosts: workers 
  become: true 
  roles:
    - Join Swarm 

- hosts: docker-manager  
  become: true 
  roles:
    - Stack Deploy


    
  

